### PR TITLE
Add support for trigger parameters inside the guard condition.

### PR DESCRIPTION
**Pull request by TheFo2sh**

### CODE REVIEW

**Comment by dannyzhan** [comment]
This really solved my issue for guard with parameters, but can we use strong typed parameter instead of "object"?

**Comment by TheFo2sh** [comment]
I think , we can but it need more time to get it working.

**Comment by HenningNT** [comment]
@TheFo2sh This is great work! Would you mind following up on the suggestion fromo @dannyzhan, and also resolve the conflicts?

**Comment by HenningNT** [comment]
Sorry, I'm closing this since it's quite old. Please let me know if you feel this is the wrong decision.

**Pull request closed without merging**
