### PR TITLE
Add portable profile 259 (.NET 4.5) and Xamarin support

### PR DESCRIPTION
**Pull request by anjdreas**
Profile 259 has become more or less the standard PCL profile when targeting .NET 4.5 in the nuget community, and is well supported by the Xamarin framework.

I'm not familiar with signed assemblies, so I'd appreciate a hand on that part.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Not sure either - just kicked off a new build, sorry about the delay.

**Comment by anjdreas** [comment]
Still not building, weird. Anyhow, decided on what path you want to go?

**Comment by anjdreas** [comment]
Just checking in on this. I've been using a custom built DLL to achieve this and it would be nice to have it in the official nuget.

**Comment by oysteinkrog** [comment]
@nblumhardt Would love it if this could be merged :)

**Comment by nblumhardt** [comment]
@oysteinkrog things have moved on a bit in time since this one; I'm keen to see it move forward though so I will close and reopen to kick off a fresh CI attempt. Cheers!

**Comment by nblumhardt** [comment]
Still failing, but seems now like the issue is the compiler version being mismatched. I think `appveyor.yml` will need some changes to get this through successfully (one improvement we've made since this PR was initially opened, so hopefully a bit easier to deal with now).

@anjdreas sorry about the hold up, are you still interested in this or should we seek a new PR?

Cheers!

**Comment by anjdreas** [comment]
@nblumhardt I'll try to rebase the PR, if that is what you meant.

**Comment by anjdreas** [comment]
Hm, seems appveyor is stuck on an old msbuild version for this PR. Is that by design on their end?
I'll try recreating the PR.

**Pull request closed without merging**
