### PR TITLE
This should take take of the internal transition handling. Now the ac…

### PR DESCRIPTION
**Pull request by HenningNT**
…tion is stored with the trigger.

I've added Sync and Async classes to the InternalTriggerBehaviour  class.

### CODE REVIEW

**Comment by HenningNT** [comment]
So.. I'll approve it myself, then ;-)

**Comment by HenningNT** [comment]
I would really like some feedback on this PR.

**Comment by HenningNT** [comment]
Espescially since I deleted: … 
 public StateConfiguration InternalTransitionIf<TArg0>(TriggerWithParameters<TArg0> trigger, Func<bool> guard, Action<TArg0, Transition> internalAction)

from StateConfiguration.cs.

**Comment by nblumhardt** [comment]
The test looks good :-) 👍

**Comment by HenningNT** [comment]
OK, I'll merge this...

**Pull request merged**
