### PR TITLE
Update Stateless.csproj to add .netstandard2.1 support

### PR DESCRIPTION
**Pull request by abuassar**
add .netstandard2.1 support

### CODE REVIEW

**Comment by abuassar** [comment]
related issue: 
https://github.com/dotnet-state-machine/stateless/issues/332

**Comment by Mephistofeles** [comment]
.NET Standard 2.1 is supported only by .NET Core 3.0. Why do you want to drop support for older versions, when there is no inherent advantage of using 2.1, when not using any new functions? 
I think it should be changed to .NET Standard 2.0, which is compatible with 2.1 projects.

**Comment by abuassar** [comment]
> 
> 
> .NET Standard 2.1 is supported only by .NET Core 3.0. Why do you want to drop support for older versions, when there is no inherent advantage of using 2.1, when not using any new functions?
> I think it should be changed to .NET Standard 2.0, which is compatible with 2.1 projects.

we can add both netstandard2.0 and netstandard2.1

**Comment by vip32** [comment]
Netstandard 2.0 should suffice. 2.1 not needed as this lib does not use any of its features.

What is holding stateless back regarding the 2.0 targeting? So it can be properly used with netcore 2/3

**Comment by vip32** [comment]
here's a proper netstandard 2.0 only PR #334

**Comment by vip32** [comment]
can be closed: netstandard2.0 support has already been merged (#334)

**Pull request closed without merging**
