### PR TITLE
Release for 4.4.0

### PR DESCRIPTION
**Pull request by HenningNT**
Releasing latest changes.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hi @HenningNT 👋 

Since this adds new targets, perhaps a minor version bump (3.5.0) is warranted?

**Comment by HenningNT** [comment]
Good point, it should be consider a new feature.

**Comment by HenningNT** [comment]
Also, the project / solution files should probably be updated as well...

**Comment by HenningNT** [comment]
Ehm, the latest on nuget is 4.3.0, so I guess the next version should be 4.4.0...

**Comment by nblumhardt** [comment]
:+1: I just updated the CSPROJ to generate 4.4.0 packages. HTH! Otherwise, ✔️ from me :-)

**Comment by HenningNT** [comment]
Thanks!
Unless there are objections I'll do the merge tomorrow.

**Pull request merged**
