### PR TITLE
Allow trigger with parameter list

### PR DESCRIPTION
**Pull request by Mafus1**
PR for Issue https://github.com/dotnet-state-machine/stateless/issues/389
I didnt implement the changes for async, but you can have a look if you think it would benefit the project.

### CODE REVIEW

**Comment by HenningNT** [comment]
Hello again!

I think I would like to merge this is, but could I ask for some unit tests that cover the new functionality?

**Comment by Mafus1** [comment]
Hi,

That's great to hear! Yes, I will add some unit test.

**Comment by Mafus1** [comment]
Hello again, 

I just added some test, I hope that's all right. If you need something else, just let me know.

**Comment by HenningNT** [comment]
Very good!

Thank you for your contribution!

**Pull request merged**
