### PR TITLE
Asynchronous guard conditions and state selectors

### PR DESCRIPTION
**Pull request by rwwilden**
Added a `GuardAsync` to `GuardCondition`, next to the existing `Guard`. This is not an ideal solution yet because it requires two separate implementation paths: `FireAsync` only checks async guards, `Fire` checks synchronous guards (I realize this is a breaking change so I should do some more work to prevent this (done: commit 262c9a1)).

Ideally, guards should always be asynchronous where synchronous guards are wrapped. However, that would be a breaking change I guess because of the divide between sync and async code via `#if TASKS`.

Also included are a couple of `PermitIf` implementations that use async guards. I have not yet implemented the complete async API surface.

Additionally, added support for asynchronous state selectors. This results in an additional field `_destinationAsync` to be added to `DynamicTriggerBehaviour` (similar to `GuardAsync` in `GuardCondition`). When calling one of the `FireAsync` overloads, any synchronous state selector is preferred over the asynchronous state selector to not break existing code.

### CODE REVIEW

**Comment by rwwilden** [comment]
Oh, by the way, the work is inspired by what was already happening in the `Support-async-conditions-in-PermitIf` branch by @HenningNT. I just added a few things.

**Comment by rwwilden** [comment]
#189

**Comment by rwwilden** [comment]
#189

**Comment by rwwilden** [comment]
@HenningNT is there something I can do to help get this PR accepted?
I'm currently using the code from my fork on a project that should go into production somewhere in November and this is not an ideal situation :)

**Comment by oising** [comment]
This looks like a good addition. Pinging @HenningNT again :)

**Comment by HenningNT** [comment]
@rwwilden , @oising Sorry about the delay, I haven't had the opportunity to follow up on this.

I'll take a look now ;-)

**Comment by HenningNT** [comment]
@rwwilden Why change OnEntryAsync to OnAsyncEntry? This would break some stuff.

**Comment by rwwilden** [comment]
@HenningNT that's a good question. I suppose because it is not actually an async method. But now it lives beside `OnExitAsync` as well which is confusing and inconsistent.

**Comment by HenningNT** [comment]
Sorry, I'm closing this since it's quite old. Please let me know if you feel this is the wrong decision.

**Pull request closed without merging**
