### PR TITLE
Convert to VS2015's project.json format

### PR DESCRIPTION
**Pull request by matt-richardson**
Updated to use VS2015's new project.json format, and ouput dll's for
net35, net40, and PCL (Profile136).
Ended up requiring an upgrade of nunit from 2.4.1 to 2.6.4, as the
binary dependencies didn't work so well.

As discussed, not sure how well this is going to work with running the tests. Let's see!

### CODE REVIEW

**Comment by matt-richardson** [comment]
Well, looks like the main project built - appears to need a `dnu restore` (or potentially `nuget restore`?) to download packages. Odd that its not doing that automatically.

Are you able to share config details for AppVeyor? Then I can try and get a parallel build going. I think it might need some work to set the version correctly as well.

**Comment by nblumhardt** [comment]
Hi Matt,

AppVeyor setup is a bit of a challenge (this is just dropped in with a bunch of personal projects, when it really needs a "team" I can add you to).

If you have the time to help with the build (which would be fantastic) it might just about be time for this project to move to its own GitHub org (and AppVeyor) team so that this kind of thing can happen more smoothly. Sound like a plan?

Cheers,
Nick

**Comment by matt-richardson** [comment]
Hi Nick

Happy to help out with this with the build. Sounds like fun.

(Amusingly, I'm not actually using the component, but happy to help out as I'm learning lots of good stuff :))

Initial thought is that I'd probably approach it by going more down the appveyor.yml approach, rather than the config via the UI. Should make life easier in future.

cheers,
Matt

**Comment by matt-richardson** [comment]
Hi Nick

Hope you had a good Christmas and New Years. 

Just a quick note to bring this back to your attention. I've got a bit of time spare now, so if you've got time to sort the appveyor team side of things, I'd like to finish this off.

cheers,
Matt

**Comment by nblumhardt** [comment]
Sorry this has been taking a while. Progress! You now have write access to a new GitHub organisation `dotnet-state-machine` that owns this project. AppVeyor bit up next :-)

**Comment by nblumhardt** [comment]
Hi Matt - AppVeyor all ready to go - can you please mail me the email address you used to sign up to AppVeyor? nblumhardt at http://nblumhardt.com :-)

**Comment by nblumhardt** [comment]
Another option - there's now an `appveyor.yml` in the repo. Merging this back into the PR, then modifying to get the build running, is probably a pretty good workflow.

**Comment by matt-richardson** [comment]
Closing until I've got the build sorted

**Comment by matt-richardson** [comment]
Hi @nblumhardt 

I'm having pain with the way the new dnx project model wants to work. It appears you no longer get all your dll's copied to your bin folder, and that conflicts with what nunit wants, when running against the net40 compiled unit tests.

Three options that I can see:
a) keep the project.json format for the unit test project, and copy the files around manually. I've managed to [get this working](https://ci.appveyor.com/project/MattRichardson/stateless/build/2.5.3#L198), but its ugly.
b) keep the unit test project as a csproj
c) flick over to xunit, as that has a dnx runner (which may not help anyway, as its a net40 component)

Thoughts?

**Comment by nblumhardt** [comment]
Hi @matt-richardson - switching to xunit has been the approach for other projects I've had to bring across. I think it should work in spite of the .NET 4 support, since the binary can be tested under a later framework version.

**Pull request closed without merging**
