### PR TITLE
Added validation to `SubstateOf`

### PR DESCRIPTION
**Pull request by smartcaveman**
Added validation against recursive substate definitions in SubstateOf.  Details of problem @ https://github.com/dotnet-state-machine/stateless/issues/121

### CODE REVIEW

**Comment by nblumhardt** [comment]
I like this in principle, but it seems inconsistent that we'd detect `S : S`, but not `S : S' : S`, i.e. cycles involving more than one state.

Would it be possible to detect the issue at the point the overflow is triggered (guessing it is during `Fire()`) and reporting there?

**Comment by HenningNT** [comment]
Although the effort of checking if the superstate is valid or not is low, I don't think it needs to be done every time Fire is executed. I think we should assume that if the state machine completes the configuration step without errors, then the configuration should be correct. So we check every parameter the user provides at the public methods...

This modified SubstateOf method checks for identical and nested identical superstates.

            public StateConfiguration SubstateOf(TState superstate)
            {
                // Check for accidental identical cyclic configuration
                if (State.Equals(superstate)) { throw new ArgumentException($"Configuring {State} as a substate of {superstate} creates an illegal cyclic configuration!"); }

                // Check for accidental identical nested cyclic configuration
                List<TState> superstates = new List<TState>();
                superstates.Add(State);

                // Build list of super states
                var activeRepresentation = _lookup(superstate);
                while (activeRepresentation.Superstate != null)
                {
                    superstates.Add(activeRepresentation.Superstate.UnderlyingState);
                    activeRepresentation = _lookup(activeRepresentation.Superstate.UnderlyingState);
                }
                if (superstates.GroupBy(n => n).Any(c => c.Count() > 1))
                { throw new ArgumentException($"Configuring {State} as a substate of {superstate} creates an illegal nested cyclic configuration!"); }

                // All checks passed, it's safe to create this configuration
                var superRepresentation = _lookup(superstate);
                _representation.Superstate = superRepresentation;
                superRepresentation.AddSubstate(_representation);
                return this;
            }

**Comment by nblumhardt** [comment]
@HenningNT aha! Good thinking 👍

**Comment by smartcaveman** [comment]
Looks good.  I'll mention one minor possible optimization that I notice: `if (superstates.GroupBy(n => n).Any(c => c.Count() > 1))` would be better as `if (superstates.GroupBy(n => n).Any(c => c.Any()))`.  I don't think it's worth changing, b/c it wouldn't make a real difference unless someone is misusing the library, but if for some reason there were a really (impractically) huge number of states it could have an impact.

Thanks for fixing this!

**Comment by smartcaveman** [comment]
Thanks!

**Comment by nblumhardt** [comment]
@smartcaveman I don't think anything's fixed - as I understand it, @HenningNT is just suggesting a way it could be approached (unless I misunderstood). Cheers!

**Comment by HenningNT** [comment]
Sorry, I didn't intend to hijack the PR, I just wanted to suggest a way to solve the problem.
If you want to, I can submit a new PR, it's up to you.

Cheers!

**Pull request closed without merging**
