### PR TITLE
Add explicit .NET 6.0 framework support

### PR DESCRIPTION
**Pull request by crozone**
Add .NET 6.0 as a target framework, with the net6.0 TFM.

Corrected the .NET 5.0 TFM from net50 to net5.0

TFM documentation reference:
https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks

### CODE REVIEW

**Comment by crozone** [comment]
Should close https://github.com/dotnet-state-machine/stateless/issues/473

**Comment by crozone** [comment]
@ffMathy and a workflow check on this one too if it's not too much trouble

**Comment by ffMathy** [comment]
There you go! 😊🙏

**Comment by crozone** [comment]
Just discovered an issue with this PR: I forgot to also add the TFM changes to the testing project as well. I'll do that in a separate PR.

**Pull request merged**
